trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'sensiProACRConnection'
  imageRepository: 'frontend'
  containerRegistry: 'sensiproacr.azurecr.io'
  kubernetesServiceConnection: 'sensiProAKSConnection'
  imageTag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and push frontend image'
  inputs:
    command: 'buildAndPush'
    repository: '$(imageRepository)'
    dockerfile: 'Dockerfile'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: |
      $(imageTag)
      latest

- script: |
    docker save -o frontend-image.tar $(containerRegistry)/$(imageRepository):$(imageTag)
    trivy image --exit-code 1 --severity HIGH,CRITICAL $(containerRegistry)/$(imageRepository):$(imageTag)
  displayName: 'Scan frontend image with Trivy'

- task: Kubernetes@1
  displayName: 'Deploy frontend to AKS'
  inputs:
    kubernetesServiceConnection: '$(kubernetesServiceConnection)'
    namespace: 'default'
    command: 'apply'
    arguments: '-f k8s/frontend-deployment.yaml -f k8s/frontend-service.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpoint: '$(dockerRegistryServiceConnection)'
    azureContainerRegistry: '$(containerRegistry)'