apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: lms-frontend  # Ajouté pour correspondre au namespace
  labels:
    app: frontend
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer  # Pour exposer le frontend publiquement