apiVersion: apps/v1
kind: Deployment
metadata:
  name: course-service-deployment
  labels:
    app: course-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: youracr.azurecr.io/course-service:latest # Remplace par ton ACR et repo
        ports:
        - containerPort: 5002
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "5002"
        - name: MONGODB_URI
          value: "mongodb://mongo:27017/course" # Ajuste si MongoDB est externe
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: jwt-secret
        - name: FRONTEND_URL
          value: "http://your-frontend-url"
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: cloudinary-cloud-name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: cloudinary-api-key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: cloudinary-api-secret
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: razorpay-key-id
        - name: RAZORPAY_SECRET
          valueFrom:
            secretKeyRef:
              name: course-service-secrets
              key: razorpay-secret
        - name: USE_REDIS
          value: "false"
        volumeMounts:
        - name: uploads
          mountPath: /usr/src/app/uploads
      volumes:
      - name: uploads
        emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0