apiVersion: v1
kind: Service
metadata:
  name: course-service-service
  namespace: default
  labels:
    app: course-service
spec:
  ports:
  - port: 5002
    targetPort: 5002
    protocol: TCP
    name: http
  selector:
    app: course-service
  type: ClusterIP