trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'sensiProACRConnection'
  kubernetesServiceConnection: 'sensiProAKSConnection'
  containerRegistry: 'sensiproacr.azurecr.io'
  imageTag: '$(Build.BuildId)'

steps:
- checkout: self

# 🔑 Login à ACR via service connection
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: 'login'
    containerRegistry: '$(dockerRegistryServiceConnection)'

# 🏗 Build et Push des images
- task: Bash@3
  displayName: 'Build and push all microservices'
  inputs:
    targetType: 'inline'
    script: |
      for dir in api-gateway auth-service user-service payment-service course-service analytics-service Client; do
        echo "Building and pushing $dir image..."
        docker build -t $(containerRegistry)/$dir:$(imageTag) -t $(containerRegistry)/$dir:latest $dir
        docker push $(containerRegistry)/$dir:$(imageTag)
        docker push $(containerRegistry)/$dir:latest
      done

# 📦 Installer Trivy
- script: |
    echo "Installing Trivy..."
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
  displayName: 'Install Trivy'

# 🔍 Scan des images avec Trivy
- script: |
    for dir in api-gateway auth-service user-service payment-service course-service analytics-service Client; do
      echo "Scanning $dir image with Trivy..."
      ./trivy image --exit-code 1 --severity HIGH,CRITICAL $(containerRegistry)/$dir:$(imageTag)
    done
  displayName: 'Scan all images with Trivy'

# 🚀 Déploiement AKS
- task: Kubernetes@1
  displayName: 'Deploy all microservices to AKS'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: 'sensiProAKSConnection'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: |
      k8s/api-gateway-deployment.yaml
      k8s/api-gateway-service.yaml
      k8s/auth-service-deployment.yaml
      k8s/auth-service-service.yaml
      k8s/course-service-deployment.yaml
      k8s/course-service-service.yaml
      k8s/payment-service-deployment.yaml
      k8s/payment-service-service.yaml
      k8s/user-service-deployment.yaml
      k8s/user-service-service.yaml
      k8s/frontend-deployment.yaml
      k8s/frontend-service.yaml
