trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'
  demands:
    - Agent.Name -equals sensipro-agent

variables:
  - group: lms-secrets   # <-- tes secrets de la Library
  - name: dockerRegistryServiceConnection
    value: 'sensiProACRConnection'
  - name: kubernetesServiceConnection
    value: 'sensiProAKSConnection'
  - name: containerRegistry
    value: 'sensiproacr.azurecr.io'
  - name: imageTag
    value: '$(Build.BuildId)'

steps:
- checkout: self

# Connexion à ACR
- task: Docker@2
  displayName: 'Login to ACR'
  inputs:
    command: 'login'
    containerRegistry: '$(dockerRegistryServiceConnection)'

# Build & push des microservices
- task: Bash@3
  displayName: 'Build and push all microservices'
  inputs:
    targetType: 'inline'
    script: |
      for dir in api-gateway auth-service user-service payment-service course-service Client; do
        echo "Building and pushing $dir image..."
        docker build -t $(containerRegistry)/$dir:$(imageTag) -t $(containerRegistry)/$dir:latest $dir
        docker push $(containerRegistry)/$dir:$(imageTag)
        docker push $(containerRegistry)/$dir:latest
      done

# Scan des images avec Trivy
- script: |
    curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b .
    for dir in api-gateway auth-service user-service payment-service course-service Client; do
      echo "Scanning $dir image with Trivy..."
      ./trivy image --exit-code 1 --severity HIGH,CRITICAL $(containerRegistry)/$dir:$(imageTag)
    done
  displayName: 'Install and scan all images with Trivy'

# Déploiement sur AKS
- task: Kubernetes@1
  displayName: 'Deploy all microservices to AKS'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceConnection: '$(kubernetesServiceConnection)'
    command: 'apply'
    arguments: |
      -n lms-gateway -f k8s/api-gateway-deployment.yaml -f k8s/api-gateway-service.yaml
      -n lms-auth -f k8s/auth-service-deployment.yaml -f k8s/auth-service-service.yaml
      -n lms-course -f k8s/course-service-deployment.yaml -f k8s/course-service-service.yaml
      -n lms-payment -f k8s/payment-service-deployment.yaml -f k8s/payment-service-service.yaml
      -n lms-user -f k8s/user-service-deployment.yaml -f k8s/user-service-service.yaml
      -n lms-frontend -f k8s/frontend-deployment.yaml -f k8s/frontend-service.yaml
