services:
  api-gateway:
    build:
      context: ./Server/src/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - FRONTEND_URL=http://localhost
      - JWT_SECRET=your-secret-key
    depends_on:
      - auth-service
      - user-service
      - payment-service
      - course-service
    volumes:
      - ./Server/src/api-gateway:/usr/src/app  # Ajusté pour le répertoire spécifique
    networks:
      - lms-network

  auth-service:
    build:
      context: ./Server/src/auth-service
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - PORT=5001
      - MONGODB_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=your-secure-jwt-secret
    depends_on:
      - mongo
    volumes:
      - ./Server/src/auth-service:/usr/src/app  # Ajusté pour le répertoire spécifique
    networks:
      - lms-network

  user-service:
    build:
      context: ./Server/src/user-service
    ports:
      - "5003:5003"
    environment:
      - NODE_ENV=development
      - PORT=5003
      - MONGODB_URI=mongodb://mongo:27017/users
      - JWT_SECRET=your-secure-jwt-secret
    depends_on:
      - mongo
    volumes:
      - ./Server/src/user-service:/usr/src/app  # Ajusté pour le répertoire spécifique
    networks:
      - lms-network

  payment-service:
    build:
      context: ./Server/src/payment-service
    ports:
      - "5004:5004"
    environment:
      - NODE_ENV=development
      - PORT=5004
      - MONGODB_URI=mongodb://mongo:27017/payments
      - RAZORPAY_KEY_ID=your-razorpay-key-id
      - RAZORPAY_SECRET=your-razorpay-secret
    depends_on:
      - mongo
    volumes:
      - ./Server/src/payment-service:/usr/src/app  # Ajusté pour le répertoire spécifique
    networks:
      - lms-network

  course-service:
    build:
      context: ./Server/src/course-service
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development
      - PORT=5002
      - MONGODB_URI=mongodb://mongo:27017/course
      - JWT_SECRET=your-secure-jwt-secret
      - FRONTEND_URL=http://localhost
      - CLOUDINARY_CLOUD_NAME=your_cloud_name
      - CLOUDINARY_API_KEY=your_api_key
      - CLOUDINARY_API_SECRET=your_api_secret
      - CLOUDINARY_SECURE=true
      - RAZORPAY_KEY_ID=your-razorpay-key-id
      - RAZORPAY_SECRET=your-razorpay-secret
      - USE_REDIS=false
    depends_on:
      - mongo
    volumes:
      - ./Server/src/course-service:/usr/src/app  # Ajusté pour le répertoire spécifique
    networks:
      - lms-network

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api-gateway
    volumes:
      - ./Client:/usr/src/app  # Pour le développement, retire en prod
    networks:
      - lms-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - lms-network

networks:
  lms-network:
    driver: bridge

volumes:
  mongo-data: