apiVersion: v1
kind: Service
metadata:
  name: user-service-service
  namespace: default
  labels:
    app: user-service
spec:
  ports:
  - port: 5003
    targetPort: 5003
    protocol: TCP
    name: http
  selector:
    app: user-service
  type: ClusterIP