apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: lms-user
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: mylmsregistry.azurecr.io/user-service:latest
        ports:
        - containerPort: 5003
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: node-env
        - name: PORT
          value: "5003"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: jwt-secret
        - name: FRONTEND_URL
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: frontend-url
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: cloudinary-cloud-name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: cloudinary-api-key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: cloudinary-api-secret
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: razorpay-key-id
        - name: RAZORPAY_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: razorpay-secret
        - name: USE_REDIS
          value: "false"
        volumeMounts:
        - name: uploads
          mountPath: /usr/src/app/uploads
      volumes:
      - name: uploads
        emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0