apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: lms-auth
type: Opaque
data:
  cloudinary-api-key: MjU3OTcyMjI3ODM4NzIy    # 257972227838722
  cloudinary-api-secret: RkxXQ1gxMVYyeVp2Zkctc0JTR3RkVDgtOUNN    # FLwCX11V2yZvfG-5BSGtdT8-9CM
  cloudinary-cloud-name: ZHFwem16ZGpj    # dqpzmzdjc
  cors-origins: aHR0cDovL2xvY2FsaG9zdDozMDAwLGh0dHA6Ly9sb2NhbGhvc3Q6MzAwMS10ZXN0    # http://localhost:3000,http://localhost:3001-test
  email-from: bm9yZXBseUB0ZXN0ZG9tYWluLmNvbQ==    # noreply@testdomain.com
  jwt-expiry: MjRI    # 24H
  jwt-secret: QVpjVVk1NkYwS3dTTWx4OEkwYlo2LzNleFkrWTlUODlZVGFsVmVVenR5RT0=    # AZcUY56F0KwSMlx8I0bZ6/3exY+Y9T89YTalVeUztyE=
  smtp-host: c210cC5nbWFpbC5jb20tdGVzdA==    # smtp.gmail.com-test
  smtp-password: WDdrOXBMOHFXMm1ONHZSNXRZNnVKOGhLOW1MMHBRMXI=    # X7k9pL8qW2mN4vR5tY6uJ8hK9mL0pQ1r
  smtp-port: NTg3    # 587
  smtp-username: dGVzdC1lbWFpbEBnbWFpbC5jb20=    # test-email@gmail.com