apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: lms-payment
  labels:
    app: payment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: payment
        image: sensiproacr.azurecr.io/payment:latest
        ports:
        - containerPort: 3004
        env:
        - name: NODE_ENV
          value: "production"
        envFrom:
        - secretRef:
            name: payment-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3004
          initialDelaySeconds: 5
          periodSeconds: 5