apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: lms-user
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: user
        image: sensiproacr.azurecr.io/user:latest
        ports:
        - containerPort: 3002
        env:
        - name: NODE_ENV
          value: "production"
        envFrom:
        - secretRef:
            name: user-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5