trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'sensiProACRConnection'
  imageRepository: 'course-service'
  containerRegistry: 'sensiproacr.azurecr.io'
  kubernetesServiceConnection: 'sensiProAKSConnection'
  imageTag: '$(Build.BuildId)'

steps:
- task: Docker@2
  displayName: 'Build and push Course Service image'
  inputs:
    command: 'buildAndPush'
    repository: '$(imageRepository)'
    dockerfile: 'Dockerfile'
    containerRegistry: '$(dockerRegistryServiceConnection)'
    tags: |
      $(imageTag)
      latest

- script: |
    docker save -o course-service-image.tar $(containerRegistry)/$(imageRepository):$(imageTag)
    trivy image --exit-code 1 --severity HIGH,CRITICAL $(containerRegistry)/$(imageRepository):$(imageTag)
  displayName: 'Scan Course Service image with Trivy'

- task: Kubernetes@1
  displayName: 'Deploy Course Service to AKS'
  inputs:
    connectionType: 'Kubernetes Service Connection'
    kubernetesServiceEndpoint: '$(kubernetesServiceConnection)'
    command: 'apply'
    arguments: '-f k8s/course-service-deployment.yaml -f k8s/course-service-service.yaml'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpoint: '$(dockerRegistryServiceConnection)'
    azureContainerRegistry: '$(containerRegistry)'