apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  namespace: default
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: api-gateway
  type: ClusterIP