trigger:
- main

variables:
  azureSubscription: 'Azure-Sensipro-Prod'
  dockerRegistry: 'sensiproc.azurecr.io'
  imageName: 'auth-service'
  k8sNamespace: 'sensipro-prod'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    
    - script: |
        cd Server/src/auth-service
        npm install
        echo "Build completed successfully"
      displayName: 'Install Dependencies'
    
    - task: Docker@2
      inputs:
        containerRegistry: '$(azureSubscription)'
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: 'Server/src/auth-service/Dockerfile'
        buildContext: 'Server/src/auth-service'
        tags: |
          $(tag)
          latest
      displayName: 'Build and Push Docker Image'

    - script: |
        docker save -o auth-service-image.tar $(dockerRegistry)/$(imageName):$(tag)
        trivy image --exit-code 1 --severity HIGH,CRITICAL $(dockerRegistry)/$(imageName):$(tag)
      displayName: 'Scan Auth Service image with Trivy'

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: DeployToAKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'sensiProAKSConnection'
        namespace: '$(k8sNamespace)'
        manifests: |
          k8s/auth-service-deployment.yaml
          k8s/auth-service-service.yaml
        containers: '$(dockerRegistry)/$(imageName):$(tag)'
      displayName: 'Deploy to AKS'