services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/auth
      - JWT_SECRET=your-secure-jwt-secret
      - FRONTEND_URL=http://localhost:3000
      - CLOUDINARY_CLOUD_NAME=dummy_cloud_name
      - CLOUDINARY_API_KEY=dummy_api_key
      - CLOUDINARY_API_SECRET=dummy_api_secret
      - CLOUDINARY_SECURE=true
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    networks:
      - auth-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=auth
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

volumes:
  mongo-data: