apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: sensipro-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      imagePullSecrets:
      - name: acr-auth
      containers:
      - name: auth-service
        image: sensiproc.azurecr.io/auth-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: node-env
        - name: PORT
          value: "5001"
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: mongo-uri
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: jwt-secret
        - name: JWT_EXPIRY
          value: "24h"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5