apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: default
  labels:
    app: payment-service
spec:
  ports:
  - port: 80
    targetPort: 5004
    protocol: TCP
  selector:
    app: payment-service
  type: LoadBalancer