apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: lms-payment
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: sensiproacr.azurecr.io/payment-service:latest
        ports:
        - containerPort: 5004
        env:
        - name: PORT
          value: "5004"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: mongo-uri
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: razorpay-key-id
        - name: RAZORPAY_SECRET
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: razorpay-secret
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: lms-secrets
              key: node-env
        readinessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 5004
          initialDelaySeconds: 15
          periodSeconds: 10